app:
  project: deploy-elibrary
  tier: application

image:
  repository: maksymhencha/educative-helm-bookapp
  tag: 0.0.2

deployments:
  containerName: deploy-elibrary
  containerPort: 3000
  imagePullPolicy: Always
  replicas: 1

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31111